export const TOKENS = {
  UserRepository: Symbol('UserRepository'),
  OtpService: Symbol('OtpService'),
  AuthService: Symbol('AuthService'),
  EmailService: Symbol('EmailService'),
  SmsService: Symbol('SmsService'),
  StylistInviteRepository: Symbol('StylistInviteRepository'),
  StylistRepository: Symbol('StylistRepository'),
  StylistInviteService: Symbol('StylistInviteService'),
  StylistService: Symbol('StylistService'),
  StylistModel: Symbol('StylistModel'),
  UserAdminService: Symbol('UserAdminService'),
  ProfileService: Symbol('ProfileService'),
  ImageService: Symbol('ImageService'),
  CategoryRepository: Symbol('CategoryRepository'),
  CategoryService: Symbol('CategoryService'),
  ServiceService: Symbol('ServiceService'),
  ServiceRepository: Symbol('ServiceRepository'),
  BranchRepository: Symbol('BranchRepository'),
  BranchService: Symbol('BranchService'),
  StylistBranchRepository: Symbol('StylistBranchRepository'),
  StylistBranchService: Symbol('StylistBranchService'),
  BranchCategoryRepository: Symbol('BranchCategoryRepository'),
  BranchCategoryService: Symbol('BranchCategoryService'),
  BranchServiceRepository: Symbol('BranchServiceRepository'),
  BranchServiceService: Symbol('BranchServiceService'),
  QueryBuilder: Symbol('QueryBuilderService'),
} as const;
